expected_items = [
    {'item_name': 'Sauce Labs Backpack',
     'item_img': '/static/media/sauce-backpack-1200x1500.0a0b85a3.jpg',
     'item_desc': 'carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.',
     'item_price': 29.99},
    {'item_name': 'Sauce Labs Bike Light',
     'item_img': '/static/media/bike-light-1200x1500.37c843b0.jpg',
     'item_desc': "A red light isn't the desired state in testing but it sure helps when riding your bike at night. Water-resistant with 3 lighting modes, 1 AAA battery included.",
     'item_price': 9.99},
    {'item_name': 'Sauce Labs Bolt T-Shirt',
     'item_img': '/static/media/bolt-shirt-1200x1500.c2599ac5.jpg',
     'item_desc': 'Get your testing superhero on with the Sauce Labs bolt T-shirt. From American Apparel, 100% ringspun combed cotton, heather gray with red bolt.',
     'item_price': 15.99},
    {'item_name': 'Sauce Labs Fleece Jacket',
     'item_img': '/static/media/sauce-pullover-1200x1500.51d7ffaf.jpg',
     'item_desc': "It's not every day that you come across a midweight quarter-zip fleece jacket capable of handling everything from a relaxing day outdoors to a busy day at the office.",
     'item_price': 49.99},
    {'item_name': 'Sauce Labs Onesie',
     'item_img': '/static/media/red-onesie-1200x1500.2ec615b2.jpg',
     'item_desc': "Rib snap infant onesie for the junior automation engineer in development. Reinforced 3-snap bottom closure, two-needle hemmed sleeved and bottom won't unravel.",
     'item_price': 7.99},
    {'item_name': 'Test.allTheThings() T-Shirt (Red)',
     'item_img': '/static/media/red-tatt-1200x1500.30dadef4.jpg',
     'item_desc': 'This classic Sauce Labs t-shirt is perfect to wear when cozying up to your keyboard to automate a few tests. Super-soft and comfy ringspun combed cotton.',
     'item_price': 15.99}
]
